Update deps eframe and egui to v0.23
This is needed so that other repos that use egui-plotter don't end up with
two versions of eframe and egui, v0.23 and v0.22. When that happens there
can be an "error[E0308]: mismatched types. Such as when the first example
in README.md is compiled.